[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y unzip && curl -fsSL https://bun.sh/install | bash && bun install && bun run build"

[deploy]
startCommand = "bun run start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 