[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y unzip && curl -fsSL https://bun.sh/install | BUN_INSTALL=/usr/local bash && ln -s /usr/local/bin/bun /usr/bin/bun && bun install && bun run build"

[deploy]
startCommand = "BUN_INSTALL=/usr/local PORT=$PORT bun run start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 